from robot import Robot

eniac = Robot()
print(eniac.set_state)
eniac.start()
print(eniac.set_state)
eniac.update(2)
print(eniac.left_motor.speed)
print(eniac.max_speed)
print(eniac.set_state)
eniac.drive(2,0.4)
print(eniac.set_state)
eniac.emergency_stop()
print(eniac.set_state)
eniac.reset()
print(eniac.set_state)
eniac.update(0.7)
print(eniac.left_motor.speed)
eniac.update(0.3)
print(eniac.left_motor.speed)
eniac.update("xxx")
print(eniac.left_motor.speed)
print(eniac.set_state)
#print(eniac.left_motor.speed,eniac.right_motor.speed,eniac.max_speed,eniac.left_motor.enabled, eniac.right_motor.enabled)