from robot import Robot

eniac = Robot()
print(eniac.state)
eniac.start()
print(eniac.state)
eniac.update(0.3)
eniac.drive("2","2")
print(eniac.state)
eniac.update(0.7)
eniac.drive(4,0)
print(eniac.state)
eniac.update(0.3)
eniac.reset()
eniac.emergency_stop()
print(eniac.state)
eniac.reset()
print(eniac.state)
eniac.start()
eniac.drive(0.5,0.1)
print(eniac.state)
eniac.reset()
print(eniac.state)
eniac.start()
print(eniac.state)
eniac.drive(4,0.4)
print(eniac.state)
eniac.update("d")
eniac.drive(4,0.4)
print(eniac.state)

#print(eniac.left_motor.speed,eniac.right_motor.speed,eniac.max_speed,eniac.left_motor.enabled, eniac.right_motor.enabled)